# Generated by Django 3.2.25 on 2024-11-14 09:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customer_service', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='servicerequest',
            name='customer',
        ),
        migrations.AddField(
            model_name='servicerequest',
            name='customer_email',
            field=models.EmailField(default='customer@example.com', max_length=254),
        ),
        migrations.AddField(
            model_name='servicerequest',
            name='customer_name',
            field=models.CharField(default='Anonymous', max_length=100),
        ),
    ]
